name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch
  pull_request:
    branches:
      - main # Optional: to deploy on pull requests

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # or your preferred version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Path to the build output directory
          destination_branch: gh-pages # You can change this if needed
